### ISSUE TITLE
I'm having a problem with the MultiPrime package. Specifically, when I use the DPrime function, I don't get any results. I'm not sure what's causing this issue

### ISSUE THREAD

**Issue by zhuxu001** [joybio/multiPrime#3]
I installed MultiPrime from PyPI and used it to design primers for a set of genomes manually (not the pipeline). However, I didn't get any results and the program consumed a lot of memory. What could be causing this issue? Are there any steps I can take to improve the performance?

**Comment by joybio** [comment]
Please update MultiPrime to version 2.3.6 or higher. I suggest using the following command: **pip install multiPrime==2.3.8**

**Comment by zhuxu001** [comment]
Thanks, it works. 
I have noticed that primers designed for specific genes or CDS tend to perform better than those designed for the entire genome. When I design primers for the same accession set, I achieve satisfactory coverage (>99%) when targeting genes or CDS, or specific regions of interest, compared to designing primers for the entire genome (~70%). Is this a common observation or are there factors that could be affecting primer performance?

**Comment by joybio** [comment]
I appreciate your attention to detail. It's important to note that the quality of the multiple sequence alignment greatly influences primer performance. Aligning longer or more input sequences can lead to worse alignments, which can negatively impact the number of candidate primers and their performance. Our team is committed to continuously improving the performance of MultiPrime.

**Comment by joybio** [comment]
It's a very good program. Thank you so much!

**Comment by zhuxu001** [comment]
I don't have any further questions at this time. The program has met my needs perfectly!. Thank you so much!

**Comment by joybio** [comment]
> I don't have any further questions at this time. The program has met my needs perfectly!. Thank you so much!

you are welcome.
